<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SignalAtlas.Core\SignalAtlas.Core.csproj" />
    <ProjectReference Include="..\..\src\SignalAtlas.Data\SignalAtlas.Data.csproj" />
    <ProjectReference Include="..\..\src\SignalAtlas.Collectors\SignalAtlas.Collectors.csproj" />
    <ProjectReference Include="..\..\src\SignalAtlas.Resources\SignalAtlas.Resources.csproj" />
    <ProjectReference Include="..\..\src\SignalAtlas.Reporting\SignalAtlas.Reporting.csproj" />
    <ProjectReference Include="..\..\src\SignalAtlas.LmStudio\SignalAtlas.LmStudio.csproj" />
    <ProjectReference Include="..\..\src\SignalAtlas.OpenAI\SignalAtlas.OpenAI.csproj" />
  </ItemGroup>

</Project>
